- name: APT | Installation
  apt: name={{ item }}
  with_items:
    - apache2
    - apache2-utils
  when: ansible_pkg_mgr == "apt"

- name: Enable common apache modules
  apache2_module: name={{ item }}
  with_items:
    - ssl
    - proxy
    - rewrite

- name: Enable default sites
  file: state=link src={{ item.src }} path={{ item.dest }}
  with_items:
    - src: /etc/apache2/sites-available/default-ssl.conf
      dest: /etc/apache2/sites-enabled/000-default-ssl.conf
    - src: /etc/apache2/sites-available/000-default.conf
      dest: /etc/apache2/sites-enabled/000-default.conf

